[package]
name = "wasmsign2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasmsign2"
path = "src/cli/main.rs"

[dependencies]
anyhow = "1.0.45"
clap = { version = "2.33.3", default-features = false, features = ["wrap_help"] }
ct-codecs = "1.1.1"
ed25519-compact = { version = "0.1.11", features = ["pem"] }
env_logger = { version = "0.9.0", default-features = false, features = ["humantime"] }
getrandom = "0.2.3"
hmac-sha256 = "1.0.0"
log = "0.4.14"
regex-automata = "0.1.10"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
