[package]
name = "wasmsign2"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
bincode = "1.3.3"
clap = { version = "2.33.3", default-features = false, features = ["wrap_help"] }
ct-codecs = "1.1.1"
ed25519-compact = "0.1.9"
env_logger = { version = "0.9.0", default-features = false, features = ["humantime"] }
getrandom = "0.2.3"
hmac-sha256 = "0.1.7"
serde = { version = "1.0.127", features = ["derive"] }
thiserror = "1.0.26"
